#****************************************************************************
# Copyright (C) 2018 pmdtechnologies ag & Infineon Technologies
#
# THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY
# KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
# PARTICULAR PURPOSE.
#
#****************************************************************************

#TODO : Come up with a smarter solution to make a new version!!!

string(TIMESTAMP CURRENT_DATE %Y%m%d)

IF(ROYALE_CUSTOMER_SUFFIX)
    set(ROYALE_VERSION "${ROYALE_VERSION_MAJOR}.${ROYALE_VERSION_MINOR}.${ROYALE_VERSION_PATCH}.${ROYALE_VERSION_BUILD}.${ROYALE_CUSTOMER_SUFFIX}" CACHE INTERNAL "" FORCE)
ELSE()
    set(ROYALE_VERSION "${ROYALE_VERSION_MAJOR}.${ROYALE_VERSION_MINOR}.${ROYALE_VERSION_PATCH}.${ROYALE_VERSION_BUILD}" CACHE INTERNAL "" FORCE)
ENDIF()
set(ROYALE_VERSION_NAME "${ROYALE_NAME}_${ROYALE_VERSION}" CACHE INTERNAL "" FORCE)
set(ROYALE_PACKAGE_NAME "${CURRENT_DATE}_${ROYALE_VERSION_NAME}" CACHE INTERNAL "" FORCE)

add_definitions (-DROYALE_VERSION_MAJOR=${ROYALE_VERSION_MAJOR})
add_definitions (-DROYALE_VERSION_MINOR=${ROYALE_VERSION_MINOR})
add_definitions (-DROYALE_VERSION_PATCH=${ROYALE_VERSION_PATCH})
add_definitions (-DROYALE_VERSION_BUILD=${ROYALE_VERSION_BUILD})

FILE(WRITE "${CMAKE_BINARY_DIR}/royale_version.prop" "ROYALE_PACKAGE_NAME=${ROYALE_PACKAGE_NAME}")

SET(ROYALE_VERSION_RC_FILE "${CMAKE_CURRENT_LIST_DIR}/rc/version.rc.in" CACHE INTERNAL "" FORCE)

FUNCTION(CREATE_ASSEMBLY_RC_FILE output_file)
    IF (${ROYALE_TARGET_PLATFORM} STREQUAL WINDOWS)  
        configure_file(
          "${ROYALE_VERSION_RC_FILE}"
          "${CMAKE_CURRENT_BINARY_DIR}/version.rc"
          @ONLY)
          
        SET("${output_file}" "${CMAKE_CURRENT_BINARY_DIR}/version.rc" PARENT_SCOPE)
    ELSE()
        SET("${output_file}" "" PARENT_SCOPE)
    ENDIF()   
ENDFUNCTION()
